#
#  Copyright (c) 2017 CA. All rights reserved.
#
#  This software may be modified and distributed under the terms
#  of the MIT license. See the LICENSE file for details.
#
version: '3'
services:
  mysqldb:
    image: mysql:5.5
    env_file:
      - ./config/otk-db.env
    volumes:
      - mysql-data-otk:/var/lib/mysql
    expose:
      - "3306"
    ports:
      - "3306:3306"

  otk:
    build:
      context: .
      dockerfile: Dockerfile.otk
    hostname: localhost
    ports:
      - "8443:8443"
    env_file:
      - ./config/otk.env
      - ./config/otk-db.env
      - ./config/otk-hostname.env
    environment:
      SSG_ADMIN_USERNAME: "admin"
      SSG_ADMIN_PASSWORD: "password"
      SSG_SSL_KEY: MIIJeQIBAzCCCT8GCSqGSIb3DQEHAaCCCTAEggksMIIJKDCCA98GCSqGSIb3DQEHBqCCA9AwggPMAgEAMIIDxQYJKoZIhvcNAQcBMBwGCiqGSIb3DQEMAQYwDgQIDpH4uM6cRPoCAggAgIIDmJt9NB0wLkQGwSPS1uUuRVK8dbwDJd15KoEgDtuXFQXmPTx0rcfIVt0bbRKxUgPz9eLKm20wsXy76z1P96J7NKAh7f82Dw+6VnXk1y/gKr6/78grOFO0KLzBUZ9CAg4nLD++nSn6DOu5ozHEqaP1CsKSL0qWE9g3/Zw+buUCOekMfdGmDEKjOdhDTnH05w74xUe/SwQ70pAsgWiN9j0yprL9KgY+ev12HsOkVBemcYNyyMi4QYI4cA5x2MsAvVd6hKKcj0EGRbm+HTF4QIPEaGNw3NIjRhaWFqKUV8nnkOy1a1qW20I/kgmB6DATVpgR1R8ub4HSRaqgFDLst49PlIJwBp1cGuiEBwEY57yEedv0epTCF0XZYAaUHhb68Id9AXkuRckWDoxVqk51FxJ5jgPwYbXhP/zws9biUaW0NcS5zyBS8to/deUdIDsyKvp5vUq/mwdS2NUN1GDJFRNXDEBcDt45Rag173rSbPR0ooqZU26frLrvIpO0c+Pp5+1IXooU0dqb0tVtw2ZX37lHCgtIuAYhZX5gKrcayN3Ly843Kvm6FD0hoKTutSuuGTIGMwxfBILzW6omkwZMqL9GNTAOzL6GnYEo7rW++4ebaGB62Ipfb4fKoiSZuNQ3NxDKBPzNePvh+n/Gg/RT2P+e+XhP2lv4NA+JL43kqbAmpFv0m2ayQF+TpW7d0XKxnmqg1OD8iax+THVWGcbhYhUAMUFkRtYoGahHm/EKiTMbe9jHYlHsyZVavylaqzsBKkyw8P6DK8hoZG9i4I/Gb449tJwWI5iJFaJKBU6VslKhuUmmCUQb7QU6V+0GLF+TkaC4vM9RYIyorl/FxeHB0D779Dwht22Mm+d3svyxFXaxfSXL5dhzIyYgAvpQCSV2quF1ZQQ4uhhfoH8oI++bHbMIm4p86FWHwk2IRqJQIjY/bIEMD+Mt9AdRzRmreU7bVumuEkLif1FwyjZc1zlmiJ2kw/GSo54l0VTZJAjo6hHNToGsqsUpQP+4UwBjaoPtvLAhQQVqSEOzugsRHmCoFvVUcb1cn3SMVBiQvr6fuPPjA5ocmsXcFoh82fA0QoATuk8uBVsTxQe2+Fv9dBSZW4ppuYEOzprC4AsQazPXTLAhSENseGpCQLmGaqfI6nVcNyuF5WpEYb9gSEaD2VQDwxjDtSnM0xSba2O5uIgmo9YexHpNGSoWCkDpZNJbv36buvCMF5alo3K2N011MIIFQQYJKoZIhvcNAQcBoIIFMgSCBS4wggUqMIIFJgYLKoZIhvcNAQwKAQKgggTuMIIE6jAcBgoqhkiG9w0BDAEDMA4ECPMJaHi8QWKrAgIIAASCBMioGXR3ofQ6jYT85DHnGIPkcCGGIcJiPCFdgfZ+4/4VsCarwZh+qnleXWZ5rOnMG4hKItud37bd5oAHRjLrSfUenRdUeVElikR9dS5tTs7PWeYvTbCmmSkdEBTeinoToxCdYYIw4KEwIZ/0Jzv1TI3+bJl46Iwmjcz30T1jyKUk4218cM5bYbP+oiVppDVgL59bmIBfmJujr/zAlRva6WQWzcWYDogG39FvwAhmr1nnEWpHvoH1KylgT8jwIDN8UdEiCewWfpfSFtrNFD4amKDmH5pENZVG5FSrnRm/VWdiydXitNF2Poe0iQY9mdJ/N2VOMudUTn3Kxp1a15vVaD7oAIor4ssqiRVwGs/2jiIPpZifz8eenfTiLMSonkl1LY3D+wgQ7Qq1BytrwJ/1I7Yd6+BUOEqRM6u+QraGvExvZteZlt/nFJ2TI9KCKCro2skeZaAumpMs8dpsgF4EPuyUpeltevOeKWMzk0Go5LSQdZoSdoij1klbRltr3dBARG42VEoB9yo296NwKx0I9s6Vcy8zvUdGMvH/L1eVNNAx+EOBG49oB5gf3WAylMK9wIXbZqpSv4fBHiX2k6segXku6OLOFx/t1a73nbyzKY8zRIiZSk7TkuX46gYun+cJQsgHaoykrl0420otCZyNgqM8vkESBkFZJxm4ePhFgnBp87svqUrCQun+Gad3ohbaXVjNla94TXfDyRYsdKSySabXzgLh6ahTylow3RrtWHdjNCRrGnKbxb1s3Htg59d8UJAo2qwi8fIbsg4CfRM9spbGooIw20b5VmiYBBz4wp4UL4Ba8nX+Bw6Ke6hZNLn9zEb9vo3aDEsKNQWwL0cNO5bTsAQ7PlgIO+TSG3JJrAmt71hj4ux5OkQ/B3os7/RijP9MoJmsZGLC3WB8U7VK3x0JaRrLQynykFQ69XRrmgn3o43GdHBMgDSvSsD7wvMDDdnJFiY93zFPlk2sBFKf3p6crWSkvycl9yCayKOl/g/IUQWk6wsH4+OVD34yaW0DGrHwgMunWUJjY5r8iDaVoM4vjF7Np10XkNkkcO+xSV3nzzpy2ZJTckDNor0XDPY40vHqI0RqrMKcTnyaltbrMRKW5wajEZ2gJlBch9vo/4IChwwPi9e/VVPkZvUgyLG1eHFfASbetzglPsWnpsHDgSpoF3wE1hJUNsHowmNmSVvELH32vwDaXgdoGfSlZ0VdeSIYfXJNE7Zco+W6ywUiqnRkWSYYtUhW+vWvqUSQoRCbqy97MrDJScfgVZwa77CJSMVD33Xx/Qhl7CdvEpFlsaypA4jRMoywyzQfkCOnBfwFU0WsErSdKostNhVmVTQwf0efG/gHF/8HaqR1YrUWXFZu3Tev2+dZdMN32dalCh2LYHlB6YonnqxFBA8ZTdlWG74gsnSCsVAAqJ2wftlND4hn41csGCdFwdYbI2nMJioaX4f2L2ToYfe/cPqQfo7MZbtr2JbMxOCAKJPFrpzIouS9KGkiY3RbhF/rXTpYqQ1QtX+XY4v2eVypI4jXG4VbaJTB35h41VZX726k+0zIw8uMfUoJ9DkBXwcSw/d32+r8dCTbK26EmRJGYMpg6jwz/dYTFLaejGt0lOuA9XjC3IyhFkOwByTdNdIxJTAjBgkqhkiG9w0BCRUxFgQUcRPOL+rOJYLQDZd5/gPEZtL/AdwwMTAhMAkGBSsOAwIaBQAEFPZF3hInx9bHKUnWUjk0fw410LQQBAjxHZpGx2zZQwICCAA=
      SSG_SSL_KEY_PASS: password
    links:
      - mysqldb

volumes:
  mysql-data-otk:
