#
#  Copyright (c) 2017 CA. All rights reserved.
#
#  This software may be modified and distributed under the terms
#  of the MIT license. See the LICENSE file for details.
#
version: '3'
services:
  otk_mysqldb:
    image: mysql:5.5
    env_file:
      - ./config/otk-db.env
    volumes:
      - mysql-data-otk:/var/lib/mysql
    expose:
      - "3306"
    ports:
      - "3306:3306"

  otk:
    build:
      context: .
      dockerfile: Dockerfile.otk
    hostname: localhost
    ports:
      - "8443:8443"
    env_file:
      - ./config/license.env
      - ./config/otk.env
      - ./config/otk-db.env
      - ./config/otk-hostname.env
    environment:
      SSG_ADMIN_USERNAME: "admin"
      SSG_ADMIN_PASSWORD: "password"
      # P12 archive containing the TLS private key and certificate of otk.mycompany.com and signed by the root CA certificate "Microgateway Test Root CA"
      SSG_SSL_KEY: MIIJ2QIBAzCCCZ8GCSqGSIb3DQEHAaCCCZAEggmMMIIJiDCCBD8GCSqGSIb3DQEHBqCCBDAwggQsAgEAMIIEJQYJKoZIhvcNAQcBMBwGCiqGSIb3DQEMAQYwDgQIrufo6ZmBbzwCAggAgIID+MapbydMY18TT0Fm/4oGZ2X6yOxkPnRLcACwHyLBRbxNVWYzPokzYDM5+pQnBIwc6hEyZr3M6EpVO3itNwWCjXa2sMsJ54MtZ45OIWUDRxnRDErtGbIJj0XSqKPN9QrAFV0p6+6lcf7anHFk6SWSqcmEPP/GAak1TKDc2NQ0yTyxykC0ksiXqvUI6d1VZsasGZ8FfV4mSOPP//6poMuYIkazd7N4eoz6aCDf6+ne9wbi+T7k01o1S10psbFsE1VVm0QbHj69hh6SjgH6uJuaoSr5V6IWDrkoGKXvipoMMJcg+3tWk6BNmv5EbRlRqQmCed2cm36G8O4fybjUY7jSYxlm2tMQXejNm1k3uooMl0xwwSgZSc+WPmk10ZI8Wx0akmvXXI/awkSwCNo9Mv00U5w8HOQtc6GCb65x+rxPI2Mw2QCNTGwkU2fayFpeqr73DfoAtSAQcpfDOb6vM9JxvH7cuQav373QKMKeW1eB6MgJqI7UEH57FRLljC/wR/4g7YZnL9rg1U7e/+fJRYQKhBM93aJXfSdlnwBLrXDKw5gs8TgdLvjsendHAPsvwemWPTTK3+MHD3gijQGUjJRCC3nbvYBCzijg1gszl4MoCiTccQuQm1ATLk1OLcCDulvweFF4iIzEDZTDp2wqdqqlEdjacAE4Q4+SNKWRd1FUgQGGIUmyqcJ8xu59cnKIckwVfgpJN8qgWdr5xi9E9Ac5qT8Rvx8xURK/I+FUQm2cSOW1t77MmxhzLVHju69SrFC3XyQhxlrQKS4gh957/pOAkFl9sUbz70oaOuzZEPtoji9xfuwBd4MDC+on2nCI6rFTYzyqKbjJnA0V/9Ke7R1vjenOrW5sF8zvajXRGFcuywjoIudYlOjd2Blmql4i3Y/2BpAaxDSGxCBWFxt171WItSl488ghgSKJDEYpd0hs8Wv/XZTVkl2cNAmbODh1t5FgJZ0BTh7h6Xp4yKZhRXGnQGsbTOjIPkV1Gdt6VyX8Mf0A4zF3I7B6mK5R0H5jrlvxEYrNnnd0QqLZcUekCJLA4tqG5+8XLha/nqE+zSFvOmfslOE3I3L3ENWLM16WzQ6k8QtcKeuE2k3LNYwrca3jcUJpCegVWEvoyL8/xVYVUIO5GCXI57s0FV5PcVbFkmS5IaZ8BCaO3yfIpBLF+so2z8u54DKF9rMrkQKGPvvHeYyqMk+5CJ752ENH+/5Dr5mkWEimiv2PDS2H4dvSieZqLnksCjbZFim2qMurliI5R/CLvC/SdWbiRfJxcqNYfTzbgbLz0pEtPgeYf6lfxexI/R/wwBcGWlh9dOOgYZ0BNBGTfBJbdJwtKsrYBa6JgRXR0HpJ0TP6DEe9MIIFQQYJKoZIhvcNAQcBoIIFMgSCBS4wggUqMIIFJgYLKoZIhvcNAQwKAQKgggTuMIIE6jAcBgoqhkiG9w0BDAEDMA4ECDKIwLFKNRp5AgIIAASCBMiqW3+ZSh3ucvebGMj3IiLkE0G+X1vNI3M4asEEmibsDQFfm6WxGTjl8UiIFU2BqMAdftL4WpOtvuNr6JxboiHTAfRBDg7jU6bK/6Gqbdj68ju/bG8j5CaJwGXXb5TbSzFrDGSIUbASYJAMgcWmbndS6/eZfMw/vnEqGH3amCrRyUPPRdWdA2yZ/CLt1IAVxmPHBWCJVFiJNC67/+pGadQzuhuOhR9TAH9CUd3qpAjg7N9xk9gQktci4tkHprK4s4WxMroUWgpVnFaLFLTi0REp/xutAOV6w5VhSuQFQlCvTRLt4UIqsqVuv8/2cFBRz1MSHjW3aV9h8tKUYUh9RdzvufV+hiTZ0jm7VO29/TvXJ4pVCCfI9QSynW/pE2sd9jKeDIDHdJVhha2IniO4SP1Bx9nKSA66hFF9UO1+MIC/J8bKqUoXAyFoueadIKf5U9U0kCa/VL0rivNCfMP1k/skM4CxXlBrWXLmMdNBIJp7RWCuawvAyR0qJ+UoorJMAPEbZ6ZZ2U1wdnlHpYW+dFPa/ebCGNjtOVVHTy39ImvZmbtF/SXKSdtjI7Wj5rakUXcgcIYbr7/Cs1oZ0ULbyRvARpFRIQOnPMoAzhhJNEx5u4r9ZK/ijqovM55vZkXAdu248HYMLpws5QnxHPXyHrNsSn21k98Clsc4xb6AOyzwRPYVm6YtRTKM6J++qn31cBvVoZch0q4LNgRnH1HIyJP3/oDBCy/K6gCdd76ko3fZzhvAx2qoQ9VhsQCbFzH6CtX6Pjmj1LNgaEY+ZBqj3lPvixeIRy2dOyIwbnUyyl5MMP8j/CLR53pi0t6J9J5Xz3r1U3uD77O24sUBhAQe+r6QWFVyWvuoBnVTiJ+X5yAFSHL21ZEgb5OeRFEIuLGoZdSjehUGiWPpADZeSiBKXf0g5W0N5wJ/7/PJpJ6IM2D2XxR9lrMMrnSfAbgzZoFb69AChMOhNI72AVvV8U6cCEXBHt/n/Xdr0CllmQzsPdVMVrCMHQy4zU18z7b8U0NVArroAsWwCWs3eks+cOlTCykIuGRsxIPE5nTcQgDCgld5M2ExTd43nD24Puuw18/TTX5/jyLNqr8GVeMf+Uw5ZRO+qb0dQNFrNecO7GMMJiZXVrRQinywlhzaMV4ZajFHHbXZcKbSQJmlhXKsKSE60KWFHl0CSIusFeo549W1BiM0jR6M64zHdIHJLUDZ+B1bwklweB7b/MvbRgXIbP01AiV35+inVYIhYe0qkLA0Cz03uNCdWcfMMSIk66XNmlPW7eyrbhMsIlIyuvaaWev/kXCiInMPUU5YLO7apoEHf1niTN4Rq7USc1LJNfGpxOZnvievyGoVBBRVY1UGZ4m5yVZacVwK78c1EL/U4oQjg0sOJo7AeWB2TXtfxLzp1gWMmO/xzzZt+biNzr1yuAnf0lf1rj9jaVDXU2W/XkcbuQ10vIW+8uc8TYstKDn6c9Sz00nZCx8D3FbezhrvbZ3c41xB9To5Ifm0ocQt1WPnfTJDijp5ADLwglOJdOpiKO/IsoJdwTRx9V1psTJRvdXQ0SQHw3WDL41l6GmDGG0N4v5VybqUwLqmTjeEpIWbOBV3Mey0lg57yFrOSAeHqAKNp1yag2QVV9CSIxgxJTAjBgkqhkiG9w0BCRUxFgQUsNQj2fB6vPkwNZiS6Ae2zJusWK8wMTAhMAkGBSsOAwIaBQAEFHC3Iq1FwOW1rJm6Zyd3cn9gYvutBAiHYkc7eyMt5gICCAA=
      SSG_SSL_KEY_PASS: password
    links:
      - otk_mysqldb

volumes:
  mysql-data-otk:
