#
#  Copyright (c) 2017 CA. All rights reserved.
#
#  This software may be modified and distributed under the terms
#  of the MIT license. See the LICENSE file for details.
#
version: '3'
services:
  otk_cassandra:
    build:
      context: .
      dockerfile: Dockerfile.cassandra
    deploy:
      resources:
        limits:
          memory: 512m
    environment:
      - OTK_KEYSPACE=otk_db
    command:
      bash /get_started/setupSchemas.sh
    volumes:
      - cassandra-otk:/var/lib/cassandra:rw
      
    expose:
      - "9042"

  otk:
    build:
      context: .
      dockerfile: Dockerfile.otk
    hostname: localhost
    ports:
      - "8443:8443"
    env_file:
      - ./config/license.env
      - ./config/otk.env
      - ./config/otk-db.env
      - ./config/otk-hostname.env
    environment:
      SSG_ADMIN_USERNAME: "admin"
      SSG_ADMIN_PASSWORD: "password"
      # P12 archive containing the TLS private key and certificate of otk and signed by the root CA certificate "Microgateway Test Root CA"
      SSG_SSL_KEY: MIIJyQIBAzCCCY8GCSqGSIb3DQEHAaCCCYAEggl8MIIJeDCCBC8GCSqGSIb3DQEHBqCCBCAwggQcAgEAMIIEFQYJKoZIhvcNAQcBMBwGCiqGSIb3DQEMAQYwDgQIeAiQk3vaZmACAggAgIID6GCvpa/ulLKMXd0qjAnu5u5vhYzQYQ+QhZ3muvR6L5aKlsCw6xe1NWob16XLEyv/YzYZ/qJthqUdeP8D1drUoAuuTYWpIN8vodEEdFrW+6oA3jqtNo8LQYY7bEtz4iSim2tHt2VuDY+DdjSngSZ7ZzOF+R+s88xgYpkV3znTSUXuv3kO+BwWd9AC8J+pd3Yn17ynoq4qmY8dFYJnQZiAxiK7OriQuo524pMxCgpVLlu5nr3L4A1QMiH8CsGQjleFa+9lLYuuYDOgY7mGdllCRKpyVvrLrJiaH3DrnGkKJyDX1CtNGwHrOHRMmxOL/Xk6ZT84W2q8KSDbWnxdS3K5g8VqjqgY0VxOz4WdCMR012ytv+7TS/nGhC54RaWjY4BYmCyul3aVBnRTGfXBztGGdkAWTJHGQI1mxYMkBT0igmfzFEswQ1dILFMH2ZZBU0TXGXxN4nolcwm7Qqpf0bTQ9+4cLbkx9Mni0B4GLGdPTiVA7uaOyCq60av+KMeXU9L7tPxVFUUMxbt3xokr4EnpbkLrSFLf6UQbPUe2/LJOgh1pWJA78TEdHyOZxwIg9BvcPmlcWIC45IZsvhQ+616fiUNylR26MJ8QJl7T3UoMK+A53ANKyh5m0agrUzHnblz1dYeejESs0czA4Z5/xjEUNl1KPxj3cv8Luvrqu34TmjtWVXItf4WkIBRgIkuedDXOFMV2oCY2eruieFUdub94zqdcDIj0TbCQYFp4sKWKEKMnMRtkCmdCXVFQEOMj50GLhM93n1NxXXZZe9Wz9cQ/kIozZxlEQehyMHiLHoUD7q4pw2d4EeR3M7RS526xSsoB6A39bM9ZyHYyw5x0tQ12lsjzLJl2dJ+0s9qO0gzIqSIn2tKewZ8OCb6HjfP965LWSiDnIPOJrUqxsd9ln6puwiTbBkLcLNTkS/lfhTi8RdEimMcSkKuMH5D+YwfxIq7MFcyOyDsmBp9bUniamisZBMpp1xipILfM6F+lEzAd5a70baCxnAtkdXwxKyjn7r0PfPbVjnIYvFjZV4VCNL2/rUnCNzIA3bprIdbknuTm7CPhnWCrIWKKV8vtSFi+W2OAkOsyIsfKnPTagllI1sWKdPt+TSNgYbRC06Kp9C7qzgpvdAWSAsYF+vBadMjL96R3r/MSG9qOvjK+ow63bsRxdPO4MikNoITXrJ4eK85j33xRshHuiVbgn/pfOwpFOPww0+/U0W/FenRmbxOjinK5nylZNSm3M0qw9ETtMeSzRxHvAx4b7dA8EhKw+lEbVZCoQWmn1cxtjPzDX1WnSalRlq2rcfAzCsBwUscIvZcrnmoplAY9eWEPcrcwggVBBgkqhkiG9w0BBwGgggUyBIIFLjCCBSowggUmBgsqhkiG9w0BDAoBAqCCBO4wggTqMBwGCiqGSIb3DQEMAQMwDgQITEWGPVm7E1MCAggABIIEyM3WpLaV/7Abgr6H5voTCi2ahNZCGOMCaNeFL1elTYv+v6AkDM+sGdS3ehRZj7IQceTrqDPL5mfSJahfd6NBHqQ5TYI2XIyoa9WdhnhE0zSkJfHewiPctPvicfHHCa/eNYLuSp6F1EH8bQ6U54lMJATw+636Nz5gzPTzF5MBUHT+ej53OgZIe5LZYvbxelMy0J4+lEM0linfIELqbDlpYJB7hVUGlMjEIxfhMterrX7k76BhSG3jXX8ENi7D2NVUWAy06HxutX8Jhm93j1hz24RCzz4aQE2cOeiyUkwYKYOj0FtQADhDLBJKoizaCCKT8kRdh4+4dZK9UZ1sTR+XJk8Y2b5NwXq6Bj1CuIYjtI8rhIXdS05FxUitBbujuTSazSTgq+OVi3vf83xqA/0NFMKOB/Knoe8oR9r+4Dsu3JUp3N05LOKBYudf7jYtPRwWUL8FoSWm3aOUdthOpcIvFeUx0XASMfNitZzZf2qyfhZz41CCz5bH3kdpkTRzVvtxelg6KdeDtJmgsHEjeet+CFYQm16WJ0IOB6fIh9IeNPHoLsGbbahAw4tcz31QKJfd4T2agBRoZs/gBQbaJ+FX6XdbdS1BogSVXNo1JV+SWskLY32AH2DmM9eUxE46U9g9j7DIQVsgBWXSlJ1f1XgZl+nnDcD654ykLcWbqBUZKPO7OeYsTnMbfn0s7d7bAw1Rrsf1qxXJJibrin1prvQi7TzzMfP/K4X14hP2hjYzhJ1KfzrCNbOvvFgpF98jk/btn5KcL2fIAbAPhPEt13Qwvw8+bjIPVCbB/xYrlUYoWJ57WnIcbsPzQCg0+tC4NMLwZnTIT6E1TClNEOm5rhuly6ncFWzEbJAbsOP7nOLZVMfp0HHub+azNkm1omdHRLvLoaup/IqcB6QReGaKnbRo8XTPCqp9oI38JExW9Ni9tzC/jAXWcafcZPr/uzLmqq2j8iAjlkou4BiIxEofR5pGhH0Rvbb/k8okwqr3H9SDDP81a9+zJViswNb8cbsEqOEbhynOUGibYoppGvGd68prKmrvrmZWB+tpFD51+AXgP8qzXYhhOf6b4W106ZpTx7yh1qtjDPMenF9nmeV1zP5GlRwNb3XyF5C716OHFmKyrftOip3oZ0ztPx/9JbcZ5KeP7Gz5rL6DklEZP1BaMOi0RaeXmZ8Gl50vMC8P980mqocUM5lTYfh/P8vJIS7Q9Cse86cEKmlQO1Mv8qAEl5H9fZv/AqJtoHZ+qYOpn/jvO0j/Mz7frphJl2poYYZ7Yd0yPKqNpItN7LEPwXImCMqucFW/el2ad/6G45vwn8nBS7f+ZtFZMHTzQS3iE6NSfRcgxbSck1BcGR6Y1+8FDZTKCgBgx4Gb2PdBvlfPv3BRcqpfFOXmtJTMk8byQcyCv+bROLUSGaVKlmdclKhnJKqTCwlpzmVa8zM8Q348frXB7XNFaSKgB97xqA3SB3Y+J/T1u19ARKfWuDW9SKiRT8xqnOrVk5KAlSdTBlDp39aug5i2qxCXnLQ/O782mA6oeiBUMQ4avlVFlOlYs/T+bPdbyVY4jOu14Uw2iCNhlHsLk7W65OgxrH/rqU9VSSTRhFnqx4gNvCexJquzZfDHiRALL6GQkkfnjEWj7DElMCMGCSqGSIb3DQEJFTEWBBS7j7EYZNZaU5EQ4xlwD9kTAzQioTAxMCEwCQYFKw4DAhoFAAQUdTwAGz8voiBCftFRS3m6hbslR30ECDhljpQNujQiAgIIAA==      
      SSG_SSL_KEY_PASS: password
    links:
      - otk_cassandra

volumes:
  cassandra-otk:
