---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: msgw
    service: msgw-svc
  name: msgw-svc
  annotations:
    description: "The Microservices Gateway service"
spec:
  selector:
    app: msgw
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: msgw-http-port
    - protocol: TCP
      port: 8443
      targetPort: 8443
      name: msgw-https-port
    - protocol: TCP
      port: 9443
      targetPort: 9443
      name: msgw-pm-port

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    ingress.kubernetes.io/ssl-passthrough: "true"
    description: "The route to expose the Microservices Gateway's HTTPS port"
  name: msgw-pm-route
spec:
  tls:
  - hosts: 
    - microgateway.mycompany.com
  rules:
  - host: microgateway.mycompany.com
    http:
      paths:
      - path: /
        backend:
          serviceName: msgw-svc
          servicePort: 8443 # named ports won't work in kube at the time of authoring the template(https://github.com/kubernetes/ingress-nginx/issues/1459)

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: msgw-hpa
spec:
  scaleTargetRef:
    kind: Deployment
    name: msgw-dc
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 75

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: msgw-dc
  labels:
    app: msgw
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: msgw
    spec:
      containers:
      - name: msgw   
        image: isl-dsdc.ca.com:5000/apim-gateway/twelvefactorgateway/develop-develop:latest
        imagePullPolicy: Always  
        resources:
          limits:
            cpu: 2500m
            memory: 2560Mi
          requests:
            cpu: 1500m
            memory: 2048Mi
        terminationMessagePath: /dev/termination-log  
        ports:
          - containerPort: 8080
          - containerPort: 8443
          - containerPort: 9443         
        env:  
          - name: SSG_ADMIN_USERNAME
            valueFrom: 
              secretKeyRef:
                name: msgw-secret
                key: ssg.adminusername
          - name:  SSG_ADMIN_PASSWORD 
            valueFrom: 
              secretKeyRef:
                name: msgw-secret
                key: ssg.adminpassword
          - name: SSG_SSL_KEY
            valueFrom: 
              secretKeyRef:
                name: msgw-secret
                key: ssg.sslkey
          - name: SSG_SSL_KEY_PASS 
            valueFrom: 
              secretKeyRef:
                name: msgw-secret
                key: ssg.sslkeypass
          - name: ACCEPT_LICENSE 
            valueFrom: 
              configMapKeyRef:
                name: license
                key: accept.license
          - name: SSG_LICENSE
            valueFrom: 
              configMapKeyRef:
                name: license
                key: ssg.license
          - name: SSG_JVM_HEAP
            value: 2048m  
          - name: SSG_INTERNAL_SERVICES
            value: "restman"
          - name: QUICKSTART_REST_MODE
            valueFrom: 
              configMapKeyRef:
                name: quickstartconfig
                key: quickstart.rest.mode
          - name: QUICKSTART_REPOSITORY_TYPE 
            valueFrom: 
              configMapKeyRef:
                name: quickstartconfig
                key: quickstart.respository.type
          - name: QUICKSTART_REPOSITORY_DB_TYPE
            valueFrom: 
              configMapKeyRef:
                name: databaseconfig
                key: quickstart.respository.db.type
          - name: QUICKSTART_REPOSITORY_DB_HOST
            valueFrom: 
              configMapKeyRef:
                name: databaseconfig
                key: quickstart.respository.db.host
          - name: QUICKSTART_REPOSITORY_DB_PORT
            valueFrom: 
              configMapKeyRef:
                name: databaseconfig
                key: quickstart.respository.db.port
          - name: QUICKSTART_REPOSITORY_DB_NAME
            valueFrom: 
              configMapKeyRef:
                name: databaseconfig
                key: quickstart.respository.db.name
          - name: QUICKSTART_REPOSITORY_DB_USER
            valueFrom:
              secretKeyRef:
                name: msgw-db-secret
                key: msgw.dbuser
          - name: QUICKSTART_REPOSITORY_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: msgw-db-secret
                key: msgw.dbpass
          - name: QUICKSTART_REPOSITORY_CONSUL_PROTOCOL 
            valueFrom: 
              configMapKeyRef:
                name: consulconfig
                key: quickstart.respository.consul.protocol
          - name: QUICKSTART_REPOSITORY_CONSUL_HOST
            valueFrom: 
              configMapKeyRef:
                name: consulconfig
                key: quickstart.respository.consul.host
          - name: QUICKSTART_REPOSITORY_CONSUL_PORT
            valueFrom: 
              configMapKeyRef:
                name: consulconfig
                key: quickstart.respository.consul.port
          - name: QUICKSTART_REPOSITORY_CONSUL_ACL_TOKEN
            valueFrom: 
              configMapKeyRef:
                name: consulconfig
                key: quickstart.respository.consul.token
          - name: OTK_SERVER_HOST
            valueFrom: 
              configMapKeyRef:
                name: otkconfig
                key: otk.server.host
          - name: OTK_SERVER_SSL_PORT
            valueFrom: 
              configMapKeyRef:
                name: otkconfig
                key: otk.server.ssl.port
        livenessProbe:
          exec:
            command:
            - /opt/docker/rc.d/diagnostic/health_check.sh
          initialDelaySeconds: 480
          periodSeconds: 15
          timeoutSeconds: 1
          successThreshold: 1
        readinessProbe:
          exec:
            command:
            - /opt/docker/rc.d/diagnostic/health_check.sh
          initialDelaySeconds: 90
          periodSeconds: 15
          timeoutSeconds: 1
          successThreshold: 1