# this lac node will have it's port exposed so that the cli process (simulating ci/cd)
# in the script will be able to deploy the api and modify it for consumption
version: '3'
services:
  # start one node of lac with port exposed to host for admin/ui access
  # this node cannot be scaled because of exposed port
  lacadmin_node:
    image: caliveapicreator/3.2-demo
    build:
      context: .
    # networks:
    #   - demo
    ports:
      - '8111:8080'
    environment:
      - service_name=lac_admin
      - service_tags=proxy:false
      - rds_hostname=lac_mysql
      - rds_port=3306
      - rds_db_name=lac_admin
      - rds_username=lac_admin
      - rds_password=cademo123
      - ca_accept_license=enu

  # Start one node of LAC without port exposed that can be dynamically scaled
  lacscale_node:
    image: caliveapicreator/3.2-demo
    build:
      context: .
    # networks:
    #  - demo
    environment:
      - SERVICE_NAME=orders_recommendations_microservice
      - SERVICE_TAGS=proxy:true,baseurl:/rest/default/svcOrders/v1/Orders, baseurl:/rest/default/svcRecs/v1/recommendations
      - RDS_HOSTNAME=lac_mysql
      - RDS_PORT=3306
      - RDS_DB_NAME=lac_admin
      - RDS_USERNAME=lac_admin
      - RDS_PASSWORD=CAdemo123

# networks:
#   demo:
#     external: true
