FROM caapim/microgateway:1.0.00

# To use loading QuickStart services from JSON files, please change to
# SCALER_ENABLE: "false" and uncomment the following line
ADD ./services/*.json /opt/SecureSpan/Gateway/node/default/etc/bootstrap/qs/
